window.MOZEK_DATA = {
  "brain": {
    "name": "Mozek",
    "tagline": "Co víme, co děláme, co řešíme",
    "icon": "🧠"
  },

  "categories": [
    { "id": "lidi",        "name": "Lidi",                "icon": "👥", "color": "#c9b1d4", "desc": "Já, Záviš, Claude — kdo dělá co" },
    { "id": "active",      "name": "Aktivní práce",        "icon": "🔥", "color": "#c8a96e", "desc": "Projekty, na kterých se právě dělá" },
    { "id": "delivered",   "name": "U klienta / Hotové",   "icon": "🚀", "color": "#7ed8a8", "desc": "Žije produkčně, klient používá" },
    { "id": "pitch-sent",  "name": "Pitche posláno",       "icon": "📤", "color": "#7aa6d4", "desc": "Nabídka u klienta, čekáme na odpověď" },
    { "id": "pitch-draft", "name": "Pitche v procesu",     "icon": "✍️", "color": "#d4a07a", "desc": "Rozdělané pitche / nabídky" },
    { "id": "internal",    "name": "Interní / Studio",     "icon": "🛠", "color": "#9c8fb8", "desc": "KSH studio infra, deploy, templaty" },
    { "id": "tooling",     "name": "Nástroje",             "icon": "🧠", "color": "#d47aa6", "desc": "Vlastní tooly co používáme při práci" },
    { "id": "temata",      "name": "Témata co řešíme",     "icon": "💭", "color": "#7ac9d4", "desc": "Otevřené decisions, čekáme na něco" },
    { "id": "znalosti",    "name": "Znalosti & odkazy",    "icon": "📚", "color": "#d47a7a", "desc": "Servery, GitHub účty, brand, externí systémy" },
    { "id": "zivot",       "name": "Život",                "icon": "🌱", "color": "#a8d47a", "desc": "Mimo studio — škola, vlastní produkty, hobby" }
  ],

  "stacks": [
    { "id": "html",   "name": "HTML",     "color": "#e8b04a" },
    { "id": "nextjs", "name": "Next.js",  "color": "#5d8fd1" },
    { "id": "mixed",  "name": "Mixed",    "color": "#a89c8e" },
    { "id": "doc",    "name": "Dokument", "color": "#7a7a7a" },
    { "id": "person", "name": "Osoba",    "color": "#c9b1d4" },
    { "id": "topic",  "name": "Téma",     "color": "#7ac9d4" },
    { "id": "ref",    "name": "Reference","color": "#d47a7a" },
    { "id": "life",   "name": "Život",    "color": "#a8d47a" }
  ],

  "projects": [
    /* LIDI */
    {
      "id": "p-maty",
      "name": "Maty — já",
      "category": "lidi",
      "stack": "person",
      "owner": "maty",
      "type": "person",
      "client": { "name": "Owner mozku" },
      "status_note": "Owner toho mozku. Vede vlastní projekty + pomáhá Závišovi s KSH Partners značkou.",
      "links": { "folder": "Maty – Claude Code/workspace" },
      "description": "Já. Email: 1matyas.kral1@gmail.com. Druhý GitHub účet: matyaskral-cyber. Pracuje primárně z Claude Code (Maty účet).",
      "tech_notes": "",
      "todo": ["Doplnit telefon", "Doplnit roli / specializaci"],
      "last_activity": "2026-05-01",
      "tags": ["maty", "owner"]
    },
    {
      "id": "p-zavis",
      "name": "Záviš Čuchna",
      "category": "lidi",
      "stack": "person",
      "owner": "shared",
      "type": "person",
      "client": { "name": "Společník — KSH Partners" },
      "status_note": "Creative Director & Developer KSH Partners. Tvář značky pro marketing. Primární vývojář na smenky.",
      "links": { "live": "https://ksh.studio", "folder": "Práce marketing/" },
      "description": "Email: zavis@ksh.studio. Sociální sítě: @ksh.studio. Primárně vyvíjí smenky. Marketing tvář.",
      "tech_notes": "Pracuje z hlavního Claude Code (Záviš účet). Smenky NEPŘEPISOVAT bez explicitní žádosti.",
      "todo": [],
      "last_activity": "2026-05-01",
      "tags": ["zavis", "spolecnik", "ksh"]
    },
    {
      "id": "p-claude",
      "name": "Claude Code",
      "category": "lidi",
      "stack": "person",
      "owner": "shared",
      "type": "person",
      "client": { "name": "AI sparring partner" },
      "status_note": "Já. Anthropic CLI agent. Maty účet (tento) + Záviš účet (paralelně).",
      "links": { "live": "https://claude.ai/code", "folder": "Maty – Claude Code/" },
      "description": "Claude Opus 4.7 (1M context). Persistent memory v ~/.claude-maty/projects/. Číst MEMORY.md pro kontext.",
      "tech_notes": "Memory types: user / feedback / project / reference. Memory PRVNÍ, pak data.js v mozek.",
      "todo": [],
      "last_activity": "2026-05-01",
      "tags": ["ai", "claude"]
    },
    {
      "id": "p-spoluprace",
      "name": "Naše spolupráce",
      "category": "lidi",
      "stack": "person",
      "owner": "shared",
      "type": "person",
      "client": { "name": "Maty + Claude (+Záviš)" },
      "status_note": "Paralelní setup: Záviš má vlastní Claude Code, Maty má vlastní. Smenky = primárně Záviš. Klientské pitche = primárně Maty.",
      "links": { "folder": "Maty – Claude Code/CLAUDE.md" },
      "description": "Pravidla: Maty nezasahuje do `smenky` (kromě case kdy hlavní Claude Code dosáhl context limitu). Sdílíme `Weby KSH/` ale s rolí dle projektu.",
      "tech_notes": "Maty preferuje: krátké odpovědi, exploratory questions = 2-3 věty s recommendation. TaskCreate pro tracking.",
      "todo": [],
      "last_activity": "2026-05-01",
      "tags": ["proces", "rules"]
    },

    /* AKTIVNÍ */
    {
      "id": "hotel-dyje",
      "name": "Hotel Dyje",
      "category": "active",
      "stack": "html",
      "owner": "maty",
      "type": "project",
      "client": { "name": "Jiří Tran", "email": "info@hoteldyje.cz", "company": "Hotel Dyje Dačice" },
      "package": "Premium — 20 990 Kč",
      "status_note": "Premium plán potvrzen, čekáme na webglobe údaje. Doména zůstává webglobe, server jde k nám (Hetzner).",
      "links": {
        "live": "https://zaviscuchna.github.io/ksh-pitches/hotel-dyje/",
        "admin_menu": "https://zaviscuchna.github.io/ksh-pitches/hotel-dyje/menu-admin.html",
        "admin_rooms": "https://zaviscuchna.github.io/ksh-pitches/hotel-dyje/rooms-admin.html",
        "repo": "https://github.com/zaviscuchna/ksh-pitches",
        "folder": "ksh-pitches/hotel-dyje",
        "docs": "Rozpracované projekty/Hotel Dyje Dačice/"
      },
      "description": "Rodinný hotel s lidovými cenami. Web (dark + gold) + dva admin panely (denní menu, ceny ubytování).",
      "tech_notes": "Dark #0d0a08, gold #c8a96e, Playfair + Inter. Admin uses localStorage (přechod na Supabase/Postgres po dodání webglobe údajů).",
      "todo": ["Reálný backend místo localStorage", "Doména webglobe → A record na Hetzner"],
      "last_activity": "2026-05-01",
      "tags": ["hotel", "restaurace", "admin-panel", "premium"]
    },
    {
      "id": "smenky",
      "name": "Směny",
      "category": "active",
      "stack": "nextjs",
      "owner": "zavis",
      "type": "project",
      "client": { "name": "Interní + komerční", "company": "KSH" },
      "status_note": "Primárně vyvíjí Záviš. Auto-deploy na Coolify, vlastní auth, QR docházka.",
      "links": {
        "live": "https://smenky-ksh.46.225.180.130.sslip.io",
        "repo": "https://github.com/zaviscuchna/Sm-ny-",
        "folder": "smenky"
      },
      "description": "SaaS pro správu směn — zaměstnanci, aplikace, role. QR docházka pro tablet (token á 3 min).",
      "tech_notes": "Next.js 16 App Router, TS, Tailwind, PostgreSQL pg, vlastní auth. ⚠️ NEPŘEPISOVAT bez žádosti.",
      "todo": ["Pokračovat na QR docházce"],
      "last_activity": "2026-04-24",
      "tags": ["saas", "auth", "qr"]
    },
    {
      "id": "alterum",
      "name": "Alterum",
      "category": "active",
      "stack": "html",
      "owner": "maty",
      "type": "project",
      "client": { "name": "Alterum" },
      "status_note": "Probíhá redesign. WebGL ColorBends animace v hero.",
      "links": {
        "live": "https://zaviscuchna.github.io/ksh-pitches/alterum/",
        "repo": "https://github.com/zaviscuchna/ksh-pitches",
        "folder": "ksh-pitches/alterum",
        "docs": "Rozpracované projekty/Alterum/"
      },
      "description": "Royal blue + pink vivid, WebGL animace v hero (Three.js CDN), overlapping sections scroll efekt. Master soubor v alterum/index.html.",
      "tech_notes": "Před pushem zkopírovat do ksh-pitches/alterum/. Palety: #0a0f3d, #002366, #ff40ff, #d4527a. Border-radius 56px.",
      "todo": ["Dokončit redesign", "WebGL výkon na mobilu"],
      "last_activity": "2026-03-24",
      "tags": ["webgl", "agentura", "redesign"]
    },

    /* PITCH POSLÁNO */
    {
      "id": "kovarna-mrakotin",
      "name": "Kovárna Mrákotín",
      "category": "active",
      "stack": "html",
      "owner": "maty",
      "type": "project",
      "client": { "name": "Kovárna Mrákotín" },
      "status_note": "Aktivně rozdělaný — web s funkčním admin panelem. Demo seed pro reset.",
      "links": {
        "live": "https://zaviscuchna.github.io/ksh-pitches/kovarna-mrakotin/",
        "folder": "kovarna-mrakotin",
        "docs": "Rozpracované projekty/Kovárna Mrákotín/"
      },
      "description": "Rozdělaný projekt s admin panelem (menu-admin.html) a demo-seed.html.",
      "todo": ["Pokračovat ve vývoji", "Konzultovat s klientem"],
      "last_activity": "2026-04-27",
      "tags": ["active", "admin-panel"]
    },
    {
      "id": "revize-tabor",
      "name": "Revize Tábor",
      "category": "delivered",
      "stack": "html",
      "owner": "maty",
      "type": "project",
      "client": { "name": "Revize Tábor" },
      "status_note": "✅ Live na Coolify. ⚠️ Leaked GitHub token v .git/config — řešit později.",
      "links": {
        "repo": "https://github.com/zaviscuchna/revize-tabor",
        "folder": "revize-tabor",
        "docs": "Rozpracované projekty/Revize Tábor/"
      },
      "description": "Web pro revizní firmu z Tábora. Lokální logo.png místo odkazu na starý Wedos WordPress.",
      "tech_notes": "Leaked PAT v configu — viz topic 't-token'.",
      "todo": ["Revoknout leaked token (až bude na řadě)"],
      "last_activity": "2026-04-20",
      "tags": ["delivered", "live", "klient-pouziva"]
    },
    {
      "id": "pizza-nonno",
      "name": "Pizzeria Dačice (Pizza Nonno)",
      "category": "pitch-sent",
      "stack": "nextjs",
      "owner": "shared",
      "type": "project",
      "client": { "name": "Pizza Nonno", "company": "Pizzeria Dačice" },
      "status_note": "Pitch poslán — 2 weby + objednávkový systém, srovnání s Woltem, splátky.",
      "links": {
        "live": "https://zaviscuchna.github.io/ksh-pitches/pizza-dacice.html",
        "folder": "pizza-nonno",
        "docs": "Rozpracované projekty/Pizzeria Dačice/"
      },
      "description": "Pizza pro Pizza Nonno (Dačice). 2 weby + ordering + porovnání s Woltem + splátky pro klienta.",
      "tech_notes": "Next.js kopie z muj-prvni-web (package.json se ještě jmenuje 'muj-prvni-web' — přejmenovat).",
      "todo": ["Přejmenovat package.json", "Dokončit ordering"],
      "last_activity": "2026-03-11",
      "tags": ["pitch", "pizza", "ordering"]
    },
    {
      "id": "padrino",
      "name": "Pizzeria Padrino JH",
      "category": "pitch-sent",
      "stack": "html",
      "owner": "maty",
      "type": "project",
      "client": { "name": "Padrino", "company": "Pizzeria Padrino Jindřichův Hradec" },
      "status_note": "Pitch odeslán 14. 3. — čeká na feedback.",
      "links": {
        "live": "https://zaviscuchna.github.io/ksh-pitches/padrino-nabidka.html",
        "folder": "ksh-pitches/padrino",
        "docs": "Rozpracované projekty/Pizzeria Padrino JH/"
      },
      "description": "Italská pizzerie v Jindřichově Hradci.",
      "todo": ["Připomenout klientovi (uplynul cca měsíc)"],
      "last_activity": "2026-03-14",
      "tags": ["pitch", "restaurace", "JH"]
    },

    /* PITCH V PROCESU */
    {
      "id": "farmarskej-kramek",
      "name": "Farmářskej Krámek Pravíkov",
      "category": "pitch-draft",
      "stack": "html",
      "owner": "maty",
      "type": "project",
      "client": { "name": "Farmářský krámek", "company": "Pravíkov" },
      "status_note": "Pitch / e-shop návrh, nedokončeno.",
      "links": {
        "live": "https://zaviscuchna.github.io/ksh-pitches/farmarskej-kramek-nabidka.html",
        "folder": "ksh-pitches/farmarskej-kramek",
        "docs": "Rozpracované projekty/Farmářskej Krámek Pravíkov/"
      },
      "description": "E-shop / web pro farmářský krámek v Pravíkově.",
      "todo": ["Dokončit návrh", "Připravit nabídku"],
      "last_activity": "2026-04-27",
      "tags": ["pitch", "eshop"]
    },
    {
      "id": "zemoto-servis",
      "name": "Zemoto Servis",
      "category": "pitch-draft",
      "stack": "html",
      "owner": "maty",
      "type": "project",
      "client": { "name": "Zemoto" },
      "status_note": "Rozpracováno.",
      "links": { "folder": "zemoto-servis" },
      "description": "Servis pro Zemoto.",
      "todo": ["Dokončit a odeslat"],
      "last_activity": "2026-03-11",
      "tags": ["pitch", "servis"]
    },
    {
      "id": "vesely",
      "name": "Veselý",
      "category": "pitch-draft",
      "stack": "html",
      "owner": "maty",
      "type": "project",
      "client": { "name": "Veselý" },
      "status_note": "Nabídka rozpracovaná.",
      "links": { "live": "https://zaviscuchna.github.io/ksh-pitches/nabidka-vesely.html" },
      "description": "Klient Veselý.",
      "todo": [],
      "last_activity": "2026-03-11",
      "tags": ["pitch"]
    },
    {
      "id": "haus-studio",
      "name": "Haus Studio",
      "category": "pitch-draft",
      "stack": "nextjs",
      "owner": "maty",
      "type": "project",
      "client": { "name": "Haus Studio" },
      "status_note": "Next.js projekt, bez gitu. 13 MB.",
      "links": { "folder": "haus-studio" },
      "description": "Klient Haus Studio.",
      "todo": ["Ujasnit stav", "Případně git repo"],
      "last_activity": "2026-03-11",
      "tags": ["pitch", "nextjs"]
    },
    {
      "id": "ksh-pitches-misc",
      "name": "Další pitche v ksh-pitches",
      "category": "pitch-draft",
      "stack": "html",
      "owner": "maty",
      "type": "project",
      "client": { "name": "Více klientů" },
      "status_note": "13 připravených složek čekajících na obsah / nabídku.",
      "links": { "folder": "ksh-pitches/" },
      "description": "Agnes Cafe, Akad Topenářství, Autokemp Náchod, Beton Pres, CRM, Farmářské JH, Hotel Komorník, Kazava, Sanitas Tábor, Sklo Mach, V Kaštanech, Záviš, Zemoto.",
      "todo": ["Roztřídit dle priority"],
      "last_activity": "2026-05-01",
      "tags": ["pitch", "draft"]
    },

    /* U KLIENTA */
    {
      "id": "olejna",
      "name": "Olejna",
      "category": "pitch-sent",
      "stack": "html",
      "owner": "maty",
      "type": "project",
      "client": { "name": "Olejna" },
      "status_note": "Pitch — odesláno klientovi, čekáme na reakci.",
      "links": { "live": "https://zaviscuchna.github.io/ksh-pitches/olejna-pitch/" },
      "description": "Pitch web pro Olejnu.",
      "todo": [],
      "last_activity": "2026-03-11",
      "tags": ["pitch", "gastronomie"]
    },
    {
      "id": "stromky-vydri",
      "name": "Stromky Vydří",
      "category": "pitch-sent",
      "stack": "html",
      "owner": "maty",
      "type": "project",
      "client": { "name": "Stromky Vydří" },
      "status_note": "Pitch — odesláno klientovi, čekáme na reakci.",
      "links": { "live": "https://zaviscuchna.github.io/ksh-pitches/stromky-vydri/" },
      "description": "Pitch web pro zahradnictví Stromky Vydří.",
      "todo": [],
      "last_activity": "2026-03-11",
      "tags": ["pitch", "zahradnictví"]
    },
    {
      "id": "golosona",
      "name": "Golosona",
      "category": "pitch-sent",
      "stack": "html",
      "owner": "maty",
      "type": "project",
      "client": { "name": "Golosona" },
      "status_note": "Pitch — odesláno klientovi, čekáme na reakci. Luxusní kavárna, Playfair + DM Sans, teplé tóny.",
      "links": { "live": "https://zaviscuchna.github.io/ksh-pitches/golosona/" },
      "description": "Pitch pro prémiovou kavárnu. Filmová atmosféra, teplá černá #0d0a08, gold #c8964a.",
      "todo": [],
      "last_activity": "2026-03-11",
      "tags": ["pitch", "kavárna", "premium"]
    },

    /* INTERNÍ / STUDIO */
    {
      "id": "ksh-partners",
      "name": "KSH Partners (web studia)",
      "category": "internal",
      "stack": "html",
      "owner": "shared",
      "type": "project",
      "client": { "name": "Vlastní — KSH" },
      "status_note": "Produkční web KSH Partners. Repo na účtu matyaskral-cyber.",
      "links": {
        "repo": "https://github.com/matyaskral-cyber/ksh-partners",
        "folder": "ksh-partners-deploy"
      },
      "description": "Korporátní web KSH Partners — index, gdpr, obchodní podmínky.",
      "tech_notes": "Druhý GitHub účet matyaskral-cyber.",
      "todo": [],
      "last_activity": "2026-04-06",
      "tags": ["studio", "ksh"]
    },
    {
      "id": "ksh-web-next",
      "name": "KSH Web (Next.js)",
      "category": "internal",
      "stack": "nextjs",
      "owner": "shared",
      "type": "project",
      "client": { "name": "Interní" },
      "status_note": "Next.js verze webu KSH. Bez gitu, 544 MB.",
      "links": { "folder": "ksh-web-next" },
      "description": "Alternativní Next.js implementace webu KSH Studia.",
      "todo": ["Rozhodnout: aktivní nebo archiv?"],
      "last_activity": "2026-03-28",
      "tags": ["studio", "rozhodnout"]
    },
    {
      "id": "ksh-new-web-test",
      "name": "KSH Web Test (s chatbotem)",
      "category": "internal",
      "stack": "html",
      "owner": "shared",
      "type": "project",
      "client": { "name": "Interní test" },
      "status_note": "Testovací HTML web s chatbotem Jarda.",
      "links": {
        "repo": "https://github.com/zaviscuchna/KSHnewWebtest",
        "folder": "KSHnewWebtest"
      },
      "description": "Test web s chatbotem 'Jarda' a lanyard funkcí.",
      "todo": ["Použít chatbot pattern v jiných projektech?"],
      "last_activity": "2026-03-30",
      "tags": ["experiment", "chatbot"]
    },
    {
      "id": "muj-prvni-web",
      "name": "Můj první web (template)",
      "category": "internal",
      "stack": "nextjs",
      "owner": "shared",
      "type": "project",
      "client": { "name": "Template / základ" },
      "status_note": "Master Next.js template — kopíruje se pro nové projekty.",
      "links": { "folder": "muj-prvni-web" },
      "description": "cp -r muj-prvni-web → nová složka. Next.js + TS + Tailwind + shadcn/ui.",
      "todo": ["Aktualizovat security headers", "Přidat KSH design system jako default"],
      "last_activity": "2026-03-11",
      "tags": ["template"]
    },
    {
      "id": "marketing",
      "name": "Marketing systém (orchestrator)",
      "category": "internal",
      "stack": "doc",
      "owner": "zavis",
      "type": "project",
      "client": { "name": "KSH brand" },
      "status_note": "Python orchestrator pro marketing posty (TT / IG / LinkedIn). Q2 cíl: 1000 TT followerů.",
      "links": { "folder": "Práce marketing/" },
      "description": "orchestrator.py + config.py. KSH brand barvy, vizitka.html, plan-q2-2026.md. Tvář: Záviš.",
      "tech_notes": "Vlastní CLAUDE.md s brand voice (česky, hovorově, bez 'řešení'/'synergie'). Primární barva #1080a8.",
      "todo": ["Q2 KPI", "Pravidelné publikování"],
      "last_activity": "2026-04-13",
      "tags": ["marketing", "ksh"]
    },

    /* NÁSTROJE */
    {
      "id": "mindmap-audit",
      "name": "Brainstorm Map (audit hra)",
      "category": "tooling",
      "stack": "html",
      "owner": "maty",
      "type": "project",
      "client": { "name": "Vlastní tool" },
      "status_note": "Drag&drop mind map — aktuálně obsahuje brainstorm hry s auditory.",
      "links": {
        "repo": "https://github.com/zaviscuchna/brainstorm-map",
        "folder": "mindmap"
      },
      "description": "HTML drag&drop brainstorm map. Generic engine — používá se pro různé brainstormy.",
      "tech_notes": "NEZASAHOVAT — samostatný projekt.",
      "todo": [],
      "last_activity": "2026-04-17",
      "tags": ["tool", "brainstorm"]
    },
    {
      "id": "mozek",
      "name": "Mozek (tento dashboard)",
      "category": "tooling",
      "stack": "html",
      "owner": "shared",
      "type": "project",
      "client": { "name": "Maty + Claude" },
      "status_note": "Vizuální + funkční mapa všeho. Slouží jako rozšířený mozek pro Claude Code.",
      "links": { "folder": "Maty – Claude Code/workspace/mozek" },
      "description": "Tento dashboard. Single HTML + data.js + assets. Single source of truth o tom co se ve studiu i v životě děje.",
      "tech_notes": "Radial mind map: 10 kategorií, ~30 uzlů. Pan + zoom + filter + search + drawer.",
      "todo": ["Doplňovat data postupně", "v2: timeline view, connections", "v2: drag&drop assets"],
      "last_activity": "2026-05-01",
      "tags": ["tool", "dashboard"]
    },
    {
      "id": "ai-viewer",
      "name": "AI Viewer",
      "category": "tooling",
      "stack": "html",
      "owner": "maty",
      "type": "project",
      "client": { "name": "Vlastní tool" },
      "status_note": "Tool na ploše — neznámá funkce. Doplnit popis.",
      "links": { "folder": "Desktop/ai-viewer/" },
      "description": "Doplnit — co tento tool dělá.",
      "todo": ["Doplnit popis a funkci"],
      "last_activity": "2026-04-27",
      "tags": ["tool", "doplnit"]
    },

    /* TÉMATA CO ŘEŠÍME */
    {
      "id": "t-webglobe",
      "name": "Webglobe migrace (Hotel Dyje)",
      "category": "temata",
      "stack": "topic",
      "owner": "maty",
      "type": "topic",
      "client": { "name": "Otevřená otázka" },
      "status_note": "Čekáme na webglobe údaje od Jiřího Trana. Doména zůstává webglobe, server přechází k nám.",
      "links": { "folder": "ksh-pitches/hotel-dyje" },
      "description": "Premium plán Hotel Dyje potvrzen. Po dodání webglobe údajů: A-record na 46.225.180.130, překlopit admin z localStorage na Postgres/Supabase.",
      "todo": ["Připomenout Jiřímu webglobe údaje", "Připravit Postgres schema pro menu + rooms"],
      "last_activity": "2026-05-01",
      "tags": ["blocked", "hotel-dyje"]
    },
    {
      "id": "t-token",
      "name": "Token v revize-tabor",
      "category": "temata",
      "stack": "topic",
      "owner": "maty",
      "type": "topic",
      "client": { "name": "Security warning" },
      "status_note": "⚠️ Plain-text GitHub PAT v revize-tabor/.git/config. Maty informován, řeší později.",
      "links": { "folder": "revize-tabor/.git/config" },
      "description": "GitHub Personal Access Token (gho_*) uložený v plain textu v git configu.",
      "tech_notes": "Než půjde repo veřejně, MUSÍ se token revoknout (i z git history).",
      "todo": ["Revoknout token", "Použít SSH nebo gh auth login"],
      "last_activity": "2026-05-01",
      "tags": ["security", "blocked-by-user"]
    },
    {
      "id": "t-ksh-web",
      "name": "Která verze webu KSH?",
      "category": "temata",
      "stack": "topic",
      "owner": "shared",
      "type": "topic",
      "client": { "name": "Otevřené rozhodnutí" },
      "status_note": "ksh-partners-deploy (HTML, live) vs ksh-web-next (Next.js, bez gitu) — která je aktuální?",
      "links": { "folder": "ksh-partners-deploy" },
      "description": "Na disku jsou dvě verze webu KSH. HTML je live na matyaskral-cyber/ksh-partners. Next.js je 544 MB bez gitu.",
      "todo": ["Probrat se Závišem", "Smazat archív / commitnout aktuální"],
      "last_activity": "2026-05-01",
      "tags": ["rozhodnout", "studio"]
    },
    {
      "id": "t-q2-marketing",
      "name": "Q2 2026 marketing KPI",
      "category": "temata",
      "stack": "topic",
      "owner": "zavis",
      "type": "topic",
      "client": { "name": "KSH brand" },
      "status_note": "Cíl: 1000 TikTok followers, 500 IG followers do konce Q2.",
      "links": { "folder": "Práce marketing/plan-q2-2026.md" },
      "description": "Plán: 4×/týden TT video, 4×/týden IG reels, 2×/týden LinkedIn. Pilíře: 40% ukázky, 25% edukace, 20% za scénou, 15% sociální důkaz.",
      "todo": ["Pravidelné publikování", "Měřit metriky týdně"],
      "last_activity": "2026-03-25",
      "tags": ["marketing", "kpi"]
    },
    {
      "id": "t-mozek-roadmap",
      "name": "Mozek — co dál",
      "category": "temata",
      "stack": "topic",
      "owner": "shared",
      "type": "topic",
      "client": { "name": "Mozek v2+" },
      "status_note": "v1 hotová. Plánováno: timeline view, connections, drag&drop assets, inline editor.",
      "links": { "folder": "Maty – Claude Code/workspace/mozek/" },
      "description": "Co rozšířit: timeline (chronologická osa), explicit connections (kdo na čem dělá / závislosti), drag&drop log a screenshotů, in-browser editor data.js.",
      "todo": ["Definovat priority v2", "Logo system pro projekty"],
      "last_activity": "2026-05-01",
      "tags": ["mozek", "v2"]
    },

    /* ZNALOSTI & ODKAZY */
    {
      "id": "k-hetzner",
      "name": "Hetzner VPS",
      "category": "znalosti",
      "stack": "ref",
      "owner": "shared",
      "type": "reference",
      "client": { "name": "Server infrastruktura" },
      "status_note": "Hlavní server studia. IP 46.225.180.130.",
      "links": { "live": "http://46.225.180.130:8000" },
      "description": "Hetzner Cloud VPS. Běží na něm Coolify v4 (port 8000) jako platformu pro deploy.",
      "tech_notes": "IP: 46.225.180.130. Coolify: http://46.225.180.130:8000. Build: Nixpacks.",
      "todo": [],
      "last_activity": "2026-05-01",
      "tags": ["server", "infra"]
    },
    {
      "id": "k-coolify",
      "name": "Coolify",
      "category": "znalosti",
      "stack": "ref",
      "owner": "shared",
      "type": "reference",
      "client": { "name": "Deploy platforma" },
      "status_note": "Self-hosted Heroku alternativa. Auto-deploy z GitHub webhook.",
      "links": { "live": "http://46.225.180.130:8000" },
      "description": "Coolify v4 na Hetzner. Auto-deploy: GitHub push → Coolify webhook → Nixpacks build.",
      "tech_notes": "Smenky a Revize-tabor deployují přes Coolify.",
      "todo": [],
      "last_activity": "2026-05-01",
      "tags": ["deploy", "infra"]
    },
    {
      "id": "k-github",
      "name": "GitHub účty",
      "category": "znalosti",
      "stack": "ref",
      "owner": "shared",
      "type": "reference",
      "client": { "name": "Verzování" },
      "status_note": "Dva účty: zaviscuchna (hlavní) + matyaskral-cyber (KSH Partners web).",
      "links": { "live": "https://github.com/zaviscuchna" },
      "description": "zaviscuchna: ksh-pitches, smenky, KSHnewWebtest, brainstorm-map, revize-tabor. matyaskral-cyber: ksh-partners.",
      "todo": [],
      "last_activity": "2026-05-01",
      "tags": ["git", "github"]
    },
    {
      "id": "k-ksh-brand",
      "name": "KSH brand identita",
      "category": "znalosti",
      "stack": "ref",
      "owner": "shared",
      "type": "reference",
      "client": { "name": "Brand guidelines" },
      "status_note": "Primární #1080a8 (KSH teal). Tmavá #0a6685. Pozadí #0d1117. Fonty: Space Grotesk + Inter.",
      "links": { "folder": "Práce marketing/" },
      "description": "Hlas: česky, hovorově, bez korporátního newspeaku. Zakázáno: 'řešení', 'synergie', 'realizujeme'. Povoleno: 'děláme', 'stavíme'.",
      "tech_notes": "ksh-logo.svg + 4 verze KSH Barvy*.png v Práce marketing/.",
      "todo": [],
      "last_activity": "2026-04-07",
      "tags": ["brand", "ksh"]
    },
    {
      "id": "k-rozpracovane",
      "name": "Rozpracované projekty (rozcestník)",
      "category": "znalosti",
      "stack": "ref",
      "owner": "maty",
      "type": "reference",
      "client": { "name": "Centrální dokumentace" },
      "status_note": "Centrální rozcestník na ploše. Každý aktivní klient má vlastní složku s PROJEKT.md a klientskými dokumenty.",
      "links": { "folder": "Desktop/Rozpracované projekty/" },
      "description": "7 podsložek: Hotel Dyje Dačice, Alterum, Revize Tábor, Kovárna Mrákotín, Pizzeria Dačice, Farmářskej Krámek Pravíkov, Pizzeria Padrino JH.",
      "tech_notes": "Klientské PDF, fotky, briefy patří sem. Web kód do Weby KSH/.",
      "todo": ["Doplnit PROJEKT.md u každého klienta"],
      "last_activity": "2026-04-27",
      "tags": ["docs", "rozcestník"]
    },
    {
      "id": "k-claude-md",
      "name": "CLAUDE.md soubory",
      "category": "znalosti",
      "stack": "ref",
      "owner": "maty",
      "type": "reference",
      "client": { "name": "Instrukce pro Claude" },
      "status_note": "3 různé CLAUDE.md soubory s instrukcemi pro Claude — každý má svůj scope.",
      "links": { "folder": "Weby KSH/" },
      "description": "1) Weby KSH/CLAUDE.md = umělecké standardy. 2) Maty – Claude Code/CLAUDE.md = pravidla pro Maty účet. 3) Rozpracované projekty/CLAUDE.md = projekt rozcestník.",
      "tech_notes": "Mozek (data.js) je živější než CLAUDE.md.",
      "todo": ["Aktualizovat CLAUDE.md o novější projekty"],
      "last_activity": "2026-05-01",
      "tags": ["claude", "instrukce"]
    },

    /* ŽIVOT */
    {
      "id": "l-skola",
      "name": "Škola",
      "category": "zivot",
      "stack": "life",
      "owner": "maty",
      "type": "life",
      "client": { "name": "Studium" },
      "status_note": "Maty studuje. Poznámky škola na ploše (zatím prázdná složka).",
      "links": { "folder": "Desktop/Poznámky škola/" },
      "description": "Doplnit: jaká škola, obor, ročník, cíle.",
      "todo": ["Doplnit info o studiu"],
      "last_activity": "2025-02-11",
      "tags": ["skola", "doplnit"]
    },
    {
      "id": "l-ginger-shot",
      "name": "Ginger Shot",
      "category": "zivot",
      "stack": "life",
      "owner": "maty",
      "type": "life",
      "client": { "name": "Vlastní" },
      "status_note": "PDF dokumenty Ginger Shot + Nálepka ŠOT v Documents/. Zřejmě vlastní produkt — doplnit kontext.",
      "links": { "folder": "Documents/" },
      "description": "Doplnit: jaký je to produkt, status, cíle.",
      "todo": ["Doplnit detaily o produktu"],
      "last_activity": "2025-09-08",
      "tags": ["produkt", "doplnit"]
    },
    {
      "id": "l-video",
      "name": "Video editing",
      "category": "zivot",
      "stack": "life",
      "owner": "maty",
      "type": "life",
      "client": { "name": "Hobby / Práce" },
      "status_note": "video test/, Dokončené edits v Documents/, CapCut. Zřejmě video editor / content creation.",
      "links": { "folder": "Desktop/video test/" },
      "description": "Doplnit: pro koho, jak často, výstupy.",
      "todo": ["Doplnit kontext"],
      "last_activity": "2026-04-27",
      "tags": ["video", "doplnit"]
    }
  ]
};
